updates:
  - package-ecosystem: "uv"
    assignees:
      - "EDM115"
    commit-message:
      include: scope
      prefix: "[dependabot/uv] "
    directory: "/"
    labels:
      - "dependabot/uv"
    pull-request-branch-name:
      separator: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Paris"

  - package-ecosystem: "github-actions"
    assignees:
      - "EDM115"
    commit-message:
      include: scope
      prefix: "[dependabot/github-actions] "
    directory: "/"
    labels:
      - "dependabot/github-actions"
    pull-request-branch-name:
      separator: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Paris"

version: 2
